# -*- coding: utf-8 -*-
"""codesilver_The Silent Real_Time Translator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D5sFCC_jyhaOm5yHgFAkm3hkQ6gy7II4

# 🏥 CodeSilver: The Silent Protocol Translator
## Bridging Clinical Language and Operational Reality

**Problem:** Hospitals operate on two incompatible languages:
- Clinical Language (diagnoses, guidelines)
- Operational Language (DRG codes, billing, prior auth)

**Solution:** Real-time ambient translation without interrupting clinicians.

---
### ⚠️ LIMITATIONS & SAFETY PROTOCOLS

1. **SYNTHETIC DATA ONLY**: Demo uses synthetic clinical scenarios
2. **NO CLINICAL DECISION SUPPORT**: Translates, doesn't advise
3. **NO AUTOMATED ACTIONS**: Human review required
4. **NOT FDA-REGULATED**: Educational/operational tool only
5. **BIAS CONSIDERATIONS**: Trained on limited synthetic examples

---

## 📦 Setup & Installation
"""

import gradio as gr
import json
import re
from typing import Dict, List, Tuple
from datetime import datetime
import os

"""## 🗄️ Public Data Sources (CMS Rules & ICD-10 Mappings)"""

# CMS DRG Mappings (Public Data - Simplified)
DRG_DATABASE = {
    "COPD": {
        "icd10": "J44.1",
        "drg_with_cc": "190",
        "drg_without_cc": "192",
        "avg_los": 2.3,
        "severity_keywords": ["severe", "acute", "respiratory failure", "hypoxemia"]
    },
    "CHF": {
        "icd10": "I50.9",
        "drg_with_cc": "291",
        "drg_without_cc": "293",
        "avg_los": 3.8,
        "severity_keywords": ["acute", "decompensated", "pulmonary edema", "cardiogenic shock"]
    },
    "Pneumonia": {
        "icd10": "J18.9",
        "drg_with_cc": "193",
        "drg_without_cc": "195",
        "avg_los": 4.2,
        "severity_keywords": ["severe", "respiratory failure", "sepsis", "hypoxemic"]
    },
    "Sepsis": {
        "icd10": "A41.9",
        "drg_with_cc": "870",
        "drg_without_cc": "872",
        "avg_los": 5.6,
        "severity_keywords": ["severe sepsis", "septic shock", "organ dysfunction", "hypotension"]
    },
    "Chest Pain": {
        "icd10": "R07.9",
        "drg_with_cc": "313",
        "drg_without_cc": "315",
        "avg_los": 1.8,
        "severity_keywords": ["acute coronary syndrome", "troponin elevation", "ST elevation"]
    }
}

# Medicare 2-Midnight Rule (Public CMS Policy)
ADMISSION_RULES = {
    "observation": {
        "max_hours": 48,
        "criteria": "Expected discharge within 2 midnights",
        "billing_codes": ["G0378", "G0379"]
    },
    "inpatient": {
        "min_expected_stay": "2+ midnights",
        "required_phrase": "reason observation insufficient",
        "billing_codes": ["DRG-based"]
    }
}

# Prior Authorization Rules (Public CMS NCDs/LCDs - Simplified)
PRIOR_AUTH_DATABASE = {
    "BiPAP": {
        "medicare": "Covered",
        "commercial": "Requires concurrent review",
        "criteria": "Respiratory failure, COPD exacerbation"
    },
    "MRI": {
        "medicare": "May require prior auth for elective",
        "commercial": "Requires prior auth",
        "criteria": "Medical necessity documentation required"
    },
    "Prednisone": {
        "medicare": "No auth needed",
        "commercial": "No auth needed",
        "criteria": "Standard formulary"
    }
}

print("✅ Public CMS data sources loaded")

"""## 🧠 AI Translation Engine (Rule-Based + LLM)"""

class CodeSilverTranslator:
    """Silent Protocol Translator - Clinical to Operational Language"""

    def __init__(self):
        self.drg_db = DRG_DATABASE
        self.auth_db = PRIOR_AUTH_DATABASE
        self.admission_rules = ADMISSION_RULES

    def analyze_clinical_text(self, clinical_text: str) -> Dict:
        """Main translation function"""

        # Extract condition
        condition = self._identify_condition(clinical_text)

        # Extract severity indicators
        severity = self._assess_severity(clinical_text, condition)

        # Extract planned interventions
        interventions = self._extract_interventions(clinical_text)

        # Determine admission status
        admission_analysis = self._analyze_admission_status(clinical_text)

        # Check prior authorization needs
        auth_requirements = self._check_prior_auth(interventions)

        # Generate documentation gaps
        doc_gaps = self._identify_documentation_gaps(clinical_text, condition, severity)

        # Calculate billing insights
        billing = self._generate_billing_insights(condition, admission_analysis)

        return {
            "condition": condition,
            "severity": severity,
            "admission_status": admission_analysis,
            "prior_auth": auth_requirements,
            "documentation_gaps": doc_gaps,
            "billing_insights": billing,
            "interventions": interventions
        }

    def _identify_condition(self, text: str) -> Dict:
        """Identify primary condition from clinical text"""
        text_lower = text.lower()

        for condition_name, details in self.drg_db.items():
            if condition_name.lower() in text_lower:
                return {
                    "name": condition_name,
                    "icd10": details["icd10"],
                    "drg_cc": details["drg_with_cc"],
                    "drg_no_cc": details["drg_without_cc"],
                    "avg_los": details["avg_los"]
                }

        return {
            "name": "Unspecified",
            "icd10": "R69",
            "drg_cc": "Unknown",
            "drg_no_cc": "Unknown",
            "avg_los": 0.0
        }

    def _assess_severity(self, text: str, condition: Dict) -> Dict:
        """Assess severity based on keywords"""
        text_lower = text.lower()

        if condition["name"] == "Unspecified":
            return {"level": "Unknown", "quantified": False, "keywords_found": []}

        condition_data = self.drg_db.get(condition["name"], {})
        severity_keywords = condition_data.get("severity_keywords", [])

        found_keywords = [kw for kw in severity_keywords if kw.lower() in text_lower]

        quantified = any([
            "o2 sat" in text_lower,
            "respiratory rate" in text_lower,
            "blood pressure" in text_lower,
            "heart rate" in text_lower,
            re.search(r'\d+%', text),  # percentages
            re.search(r'\d+/\d+', text)  # BP or fractions
        ])

        if found_keywords:
            level = "Severe" if len(found_keywords) >= 2 else "Moderate"
        else:
            level = "Mild"

        return {
            "level": level,
            "quantified": quantified,
            "keywords_found": found_keywords
        }

    def _extract_interventions(self, text: str) -> List[str]:
        """Extract planned interventions"""
        interventions = []
        text_lower = text.lower()

        intervention_patterns = {
            "Prednisone": ["prednisone", "steroid"],
            "BiPAP": ["bipap", "bi-pap", "non-invasive ventilation"],
            "MRI": ["mri", "magnetic resonance"],
            "Nebulizer": ["nebulizer", "albuterol", "inhaler"],
            "IV Fluids": ["iv fluids", "intravenous", "bolus"]
        }

        for intervention, patterns in intervention_patterns.items():
            if any(pattern in text_lower for pattern in patterns):
                interventions.append(intervention)

        return interventions

    def _analyze_admission_status(self, text: str) -> Dict:
        """Analyze admission vs observation status"""
        text_lower = text.lower()

        # Extract time mentions
        time_patterns = {
            "24 hours": 1,
            "48 hours": 2,
            "1 day": 1,
            "2 days": 2,
            "3 days": 3
        }

        expected_days = 0
        for pattern, days in time_patterns.items():
            if pattern in text_lower:
                expected_days = max(expected_days, days)

        # Determine status
        if expected_days == 0:
            expected_days = 2  # default assumption

        if "admit" in text_lower or "admission" in text_lower:
            status = "Inpatient Admission Likely"
        elif "observe" in text_lower or "observation" in text_lower:
            status = "Outpatient Observation"
        elif expected_days < 2:
            status = "Outpatient Observation"
        else:
            status = "Inpatient Admission Likely"

        return {
            "current_status": status,
            "expected_los_days": expected_days,
            "two_midnight_rule": expected_days >= 2,
            "day_count": f"Day 1 of {expected_days}"
        }

    def _check_prior_auth(self, interventions: List[str]) -> List[Dict]:
        """Check prior authorization requirements"""
        auth_results = []

        for intervention in interventions:
            if intervention in self.auth_db:
                auth_info = self.auth_db[intervention]
                auth_results.append({
                    "intervention": intervention,
                    "medicare": auth_info["medicare"],
                    "commercial": auth_info["commercial"],
                    "criteria": auth_info["criteria"]
                })

        return auth_results

    def _identify_documentation_gaps(self, text: str, condition: Dict, severity: Dict) -> List[str]:
        """Identify missing documentation elements"""
        gaps = []
        text_lower = text.lower()

        # Severity quantification
        if not severity["quantified"]:
            gaps.append(
                f"⚠️ SEVERITY NOT QUANTIFIED: Consider documenting specific vitals "
                f"(O2 sat, respiratory rate, etc.) to support '{severity['level']}' classification"
            )

        # Admission justification
        if "admit" in text_lower or "admission" in text_lower:
            if "reason" not in text_lower and "insufficient" not in text_lower:
                gaps.append(
                    "⚠️ ADMISSION JUSTIFICATION: If converting from observation to inpatient, "
                    "must document 'reason observation insufficient'"
                )

        # Comorbidity documentation
        if condition["name"] != "Unspecified":
            cc_keywords = ["diabetes", "hypertension", "ckd", "renal", "cardiac"]
            has_cc = any(kw in text_lower for kw in cc_keywords)
            if not has_cc:
                gaps.append(
                    "💡 COMORBIDITY CHECK: Consider documenting relevant comorbid conditions "
                    "to support CC/MCC status (affects DRG assignment)"
                )

        return gaps

    def _generate_billing_insights(self, condition: Dict, admission: Dict) -> Dict:
        """Generate billing and coding insights"""
        insights = {
            "icd10": condition["icd10"],
            "drg_range": f"{condition['drg_cc']} (with CC) or {condition['drg_no_cc']} (without CC)",
            "expected_los": condition["avg_los"],
            "status_codes": [],
            "recommendations": []
        }

        # Status-specific codes
        if "Observation" in admission["current_status"]:
            insights["status_codes"] = ["G0378", "G0379"]
            if admission["expected_los_days"] == 1:
                insights["recommendations"].append(
                    "If discharged today: E/M 99221-99223 (admit) + 99234-99236 (obs same day)"
                )
        else:
            insights["status_codes"] = [f"DRG {condition['drg_cc']}"]
            insights["recommendations"].append(
                f"Anticipated LOS: {condition['avg_los']} days (benchmark)"
            )

        return insights

    def format_output(self, analysis: Dict) -> str:
        """Format analysis as operational summary"""
        output = []
        output.append("═" * 60)
        output.append("📋 OPERATIONAL TRANSLATION - READY FOR UTILIZATION REVIEW")
        output.append("═" * 60)
        output.append("")

        # Condition
        cond = analysis["condition"]
        output.append(f"🔍 SUSPECTED CONDITION: {cond['name']} ({cond['icd10']})")
        output.append("")

        # Documentation Gaps
        if analysis["documentation_gaps"]:
            for gap in analysis["documentation_gaps"]:
                output.append(gap)
            output.append("")

        # Status Alert
        adm = analysis["admission_status"]
        output.append("💰 STATUS ALERT:")
        output.append(f"   Current: {adm['current_status']}")
        output.append(f"   Timeline: {adm['day_count']}")
        if adm['two_midnight_rule']:
            output.append("   ⚠️ 2-Midnight Rule: Expected stay ≥2 midnights → Inpatient admission appropriate")
        else:
            output.append("   ⚠️ 2-Midnight Rule: Expected stay <2 midnights → Observation status appropriate")
        output.append("")

        # Prior Authorization
        if analysis["prior_auth"]:
            output.append("🛑 PRIOR AUTHORIZATION:")
            for auth in analysis["prior_auth"]:
                output.append(f"   • {auth['intervention']}:")
                output.append(f"     - Medicare: {auth['medicare']}")
                output.append(f"     - Commercial: {auth['commercial']}")
            output.append("")

        # Billing Insights
        billing = analysis["billing_insights"]
        output.append("📄 BILLING INSIGHT:")
        output.append(f"   ICD-10: {billing['icd10']}")
        output.append(f"   DRG: {billing['drg_range']}")
        output.append(f"   Expected LOS: {billing['expected_los']} days")
        for rec in billing["recommendations"]:
            output.append(f"   • {rec}")
        output.append("")

        output.append("═" * 60)
        output.append("✅ ZERO-CLICK TRANSLATION COMPLETE")
        output.append("No pop-ups. No interruptions. Just visibility.")
        output.append("═" * 60)

        return "\n".join(output)

# Initialize translator
translator = CodeSilverTranslator()
print("✅ CodeSilver Translator initialized")

"""## 📝 Synthetic Clinical Scenarios (Public/Synthetic Data)"""

EXAMPLE_SCENARIOS = {
    "COPD Exacerbation": """Mr. Jones has worsening COPD exacerbation, not responding to nebulizers.
Starting prednisone 60mg, observe for 24 hours, if no improvement we may need to admit.
Patient currently on 2L O2, respiratory rate 24.""",

    "CHF Decompensation": """Mrs. Smith presents with acute decompensated CHF, bilateral lower extremity edema,
JVD noted. Starting IV Lasix 40mg, will admit for telemetry monitoring and diuresis.
Expect 3-4 day stay. Patient has history of diabetes and hypertension.""",

    "Chest Pain - Observation": """65yo male with atypical chest pain, troponin negative x2, EKG normal.
Plan for observation unit, cardiac monitoring for 24 hours with repeat troponin.
If remains stable, discharge with outpatient stress test.""",

    "Pneumonia Admission": """Patient presents with severe pneumonia, O2 sat 88% on room air,
respiratory rate 28. CXR shows bilateral infiltrates. Starting IV antibiotics,
will need inpatient admission for at least 48-72 hours. Patient also has CKD stage 3.""",

    "Sepsis with Shock": """72yo female with sepsis, suspected UTI source. Blood pressure 85/50 despite
2L IV fluid bolus. Lactate 4.2. Will admit to ICU, start vasopressors and broad-spectrum antibiotics.
Expected stay 5-7 days minimum."""
}

print(f"✅ Loaded {len(EXAMPLE_SCENARIOS)} synthetic clinical scenarios")

"""## 🎨 Gradio UI - Interactive Demo"""

def process_clinical_note(clinical_text: str, scenario_name: str = None) -> Tuple[str, str]:
    """Process clinical text and return formatted output"""

    if not clinical_text or clinical_text.strip() == "":
        return "⚠️ Please enter clinical text or select an example scenario.", ""

    try:
        # Run translation
        analysis = translator.analyze_clinical_text(clinical_text)

        # Format output
        operational_summary = translator.format_output(analysis)

        # Generate risk metrics
        risk_score = calculate_denial_risk(analysis)
        metrics = f"""📊 REAL-TIME METRICS:

Denial Risk Score: {risk_score}/10
Documentation Gaps: {len(analysis['documentation_gaps'])}
Prior Auth Required: {len(analysis['prior_auth'])} interventions
Status: {analysis['admission_status']['current_status']}
Expected LOS: {analysis['admission_status']['expected_los_days']} days
"""

        return operational_summary, metrics

    except Exception as e:
        return f"❌ Error processing text: {str(e)}", ""

def calculate_denial_risk(analysis: Dict) -> int:
    """Calculate claim denial risk score (0-10)"""
    risk = 0

    # Documentation gaps add risk
    risk += min(len(analysis["documentation_gaps"]) * 2, 5)

    # Unquantified severity adds risk
    if not analysis["severity"]["quantified"]:
        risk += 2

    # Prior auth issues add risk
    for auth in analysis["prior_auth"]:
        if "requires" in auth["commercial"].lower():
            risk += 1

    return min(risk, 10)

def load_example(scenario_name: str) -> str:
    """Load example scenario"""
    return EXAMPLE_SCENARIOS.get(scenario_name, "")

# Create Gradio Interface
with gr.Blocks(title="CodeSilver: Silent Protocol Translator", theme=gr.themes.Soft()) as demo:

    gr.Markdown("""
    # 🏥 CodeSilver: The Silent Protocol Translator
    ### Bridging Clinical Language and Operational Reality

    **How it works:** Enter a clinical note from morning rounds, and CodeSilver will silently generate
    a parallel operational summary for billing/revenue cycle teams—with zero interruption to clinicians.

    ---

    ⚠️ **DEMO ONLY** - Uses synthetic data. Not for clinical use. Educational purposes only.
    """)

    with gr.Row():
        with gr.Column(scale=1):
            gr.Markdown("### 👨‍⚕️ Clinical Input (What Doctors Say)")

            scenario_dropdown = gr.Dropdown(
                choices=list(EXAMPLE_SCENARIOS.keys()),
                label="Load Example Scenario",
                value=None
            )

            clinical_input = gr.Textbox(
                label="Clinical Note / Morning Report",
                placeholder="Enter clinical text here... (e.g., 'Patient with COPD exacerbation, starting prednisone...')",
                lines=8
            )

            translate_btn = gr.Button("🔄 Translate to Operational Language", variant="primary", size="lg")

            gr.Markdown("""
            **Try the examples above** or write your own clinical scenario!
            """)

        with gr.Column(scale=1):
            gr.Markdown("### 💼 Operational Output (What Hospitals Need)")

            operational_output = gr.Textbox(
                label="Silent Operational Translation",
                lines=20,
                interactive=False
            )

            metrics_output = gr.Textbox(
                label="Risk Metrics",
                lines=6,
                interactive=False
            )

    gr.Markdown("""
    ---

    ### 🎯 What Makes CodeSilver Different?

    | Traditional Systems | CodeSilver |
    |-------------------|------------|
    | Pop-up alerts interrupt clinicians | Zero interruptions - silent background processing |
    | Coders review charts after discharge | Real-time operational awareness during care |
    | Claim denials discovered weeks later | Documentation gaps flagged immediately |
    | Clinicians speak one language, billers another | Automatic bidirectional translation |

    ---

    ### ⚠️ LIMITATIONS & SAFETY:

    1. **Synthetic Data Only** - This demo uses synthetic clinical scenarios
    2. **No Clinical Decision Support** - Translates language, does not advise care
    3. **Human Review Required** - All outputs must be reviewed by certified coders
    4. **Not FDA-Regulated** - Educational/operational tool only
    5. **No PHI** - Does not process real patient data

    ---

    **Built with:** Public CMS data (DRG mappings, 2-Midnight Rule, NCDs/LCDs) + Synthetic clinical examples

    **Data Sources:**
    - CMS DRG Grouper Logic (Public)
    - Medicare 2-Midnight Rule Documentation (Public)
    - ICD-10-CM Official Guidelines (Public)
    - Synthetic clinical scenarios (No PHI)
    """)

    # Wire up the interactions
    scenario_dropdown.change(
        fn=load_example,
        inputs=[scenario_dropdown],
        outputs=[clinical_input]
    )

    translate_btn.click(
        fn=process_clinical_note,
        inputs=[clinical_input, scenario_dropdown],
        outputs=[operational_output, metrics_output]
    )

print("✅ Gradio interface created")

"""## 🚀 Launch the Demo"""

# Launch the Gradio app
demo.launch(
    share=True,  # Creates public link
    debug=True,
    show_error=True
)

print("""\n
═══════════════════════════════════════════════════════════════
🎉 CodeSilver is now running!
═══════════════════════════════════════════════════════════════

Click the public URL above to access the demo.
Share the link with hackathon judges!

💡 TIP: Try all 5 example scenarios to see different translations.

═══════════════════════════════════════════════════════════════
""")

"""## 📊 Optional: Validation Metrics"""

# Run validation on all example scenarios
print("\n" + "="*60)
print("🧪 VALIDATION: Testing all synthetic scenarios")
print("="*60 + "\n")

for scenario_name, clinical_text in EXAMPLE_SCENARIOS.items():
    print(f"\n📋 Testing: {scenario_name}")
    print("-" * 60)

    analysis = translator.analyze_clinical_text(clinical_text)

    print(f"✅ Condition: {analysis['condition']['name']} ({analysis['condition']['icd10']})")
    print(f"✅ Severity: {analysis['severity']['level']}")
    print(f"✅ Status: {analysis['admission_status']['current_status']}")
    print(f"✅ Documentation Gaps: {len(analysis['documentation_gaps'])}")
    print(f"✅ Denial Risk: {calculate_denial_risk(analysis)}/10")

print("\n" + "="*60)
print("✅ All scenarios processed successfully!")
print("="*60)